version: '3'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GADATA
      MYSQL_USER: GADATA
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
  mft:
    image: myga:latest
    container_name: goanywhere-mft-1
    restart: unless-stopped
    networks:
      - default
#      default:
#        mac_address: 02:42:c0:a8:99:99
#   Uncomment the following line if adding or enabling any environment variables
    environment:
#   Uncomment the following line and update to TRUE to enable automated cluster setup.
      - MFT_CLUSTER=TRUE
#   Uncomment the following line and update it to increase Java Max Memory. Supplied amount will be in MB.
#     - JAVA_MAX_MEMORY=2048
    ports:
      # Standard ports used by GoAnywhere MFT
      - "8000-8001:8000-8001"
      - "8005-8006:8005-8006"
      - "8009-8010:8009-8010"
      - "8443:8443"
      - "8021:8021"
      - "8990:8990"
      - "8022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
      - "32001-32100:32001-32100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
      - "32101-32200:32101-32200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
      - "32201-32300:32201-32300"
    volumes:
      #- /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
      - cluster_dir:/opt/HelpSystems/GoAnywhere/cluster
      - userdata1:/opt/HelpSystems/GoAnywhere/userdata/
      - upgraderlogs1:/opt/HelpSystems/GoAnywhere/upgrader/logs/
      - configdir1:/etc/HelpSystems/GoAnywhere/config/
      - tomcatserver1:/etc/HelpSystems/GoAnywhere/tomcat/conf/
      - tomcatlogsdir1:/opt/HelpSystems/GoAnywhere/tomcat/logs/
      - ghttpsrootcustomdir1:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
      - ${HOME}/volumes/shareduserdata:/opt/HelpSystems/GoAnywhere/shareduserdata/
    depends_on:
      - mariadb
#  mft2:
#    image: myga:latest
#    container_name: goanywhere-mft-2
#    restart: unless-stopped
#    networks:
#      default:
#        mac_address: 02:42:c0:a8:99:99
#   Uncomment the following line if adding or enabling any environment variables
#    environment:
#   Uncomment the following line and update to TRUE to enable automated cluster setup.
#      - MFT_CLUSTER=TRUE
#   Uncomment the following line and update it to increase Java Max Memory. Supplied amount will be in MB.
#     - JAVA_MAX_MEMORY=2048
#    ports:
      # Standard ports used by GoAnywhere MFT
#      - "9000-9001:8000-8001"
#      - "9005-9006:8005-8006"
#      - "9009-9010:8009-8010"
#      - "9443:8443"
#      - "9021:8021"
#      - "9990:8990"
#      - "9022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
#      - "42001-42100:42001-42100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
#      - "42101-42200:42101-42200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
#      - "42201-42300:42201-42300"
#    volumes:
      #- /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
#      - cluster_dir:/opt/HelpSystems/GoAnywhere/cluster
#      - userdata2:/opt/HelpSystems/GoAnywhere/userdata/
#      - upgraderlogs2:/opt/HelpSystems/GoAnywhere/upgrader/logs/
#      - configdir2:/etc/HelpSystems/GoAnywhere/config/
#      - tomcatserver2:/etc/HelpSystems/GoAnywhere/tomcat/conf/
#      - tomcatlogsdir2:/opt/HelpSystems/GoAnywhere/tomcat/logs/
#      - ghttpsrootcustomdir2:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
#      - ${HOME}/volumes/shareduserdata:/opt/HelpSystems/GoAnywhere/shareduserdata/
#    depends_on:
#      - mariadb
volumes:
  mariadb-data:
  cluster_dir:
  userdata1:
  configdir1:
  upgraderlogs1:
  tomcatserver1:
  tomcatlogsdir1:
  ghttpsrootcustomdir1:
  userdata2:
  configdir2:
  upgraderlogs2:
  tomcatserver2:
  tomcatlogsdir2:
  ghttpsrootcustomdir2:
