version: '3'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GADATA
      MYSQL_USER: GADATA
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  mft1:
    image: myga:latest
    container_name: goanywhere-mft-1
    restart: unless-stopped
    networks:
      default:
        mac_address: 02:42:c0:a8:99:99
    ports:
      # Standard ports used by GoAnywhere MFT
      - "9000-9001:8000-8001"
      - "9005-9006:8005-8006"
      - "9009-9010:8009-8010"
      - "9443:9443"
      - "9021:8021"
      - "9990:8990"
      - "9022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
      - "32001-32100:32001-32100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
      - "32101-32200:32101-32200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
      - "32201-32300:32201-32300"
    volumes:
      - /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
      - userdata:/opt/HelpSystems/GoAnywhere/userdata/
      - ${HOME}/volumes/upgraderlogs:/opt/HelpSystems/GoAnywhere/upgrader/logs/
      - configdir:/etc/HelpSystems/GoAnywhere/config/
      - tomcatserver:/etc/HelpSystems/GoAnywhere/tomcat/conf/
      - ${HOME}/volumes/tomcatlogsdir:/opt/HelpSystems/GoAnywhere/tomcat/logs/
      - ${HOME}/volumes/ghttpsrootcustomdir:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
    depends_on:
      - mysqldb
  mft2:
    image: myga:latest
    container_name: goanywhere-mft-2
    restart: unless-stopped
    networks:
      default:
        mac_address: 02:42:c0:a8:99:99
    ports:
      # Standard ports used by GoAnywhere MFT
      - "10000-10001:8000-8001"
      - "10005-10006:8005-8006"
      - "10009-10010:8009-8010"
      - "10443:9443"
      - "10021:8021"
      - "10990:8990"
      - "10022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
      - "33001-33100:32001-32100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
      - "33101-33200:32101-32200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
      - "33201-33300:32201-32300"
    volumes:
      - /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
      - userdata:/opt/HelpSystems/GoAnywhere/userdata/
      - ${HOME}/volumes/upgraderlogs:/opt/HelpSystems/GoAnywhere/upgrader/logs/
      - configdir:/etc/HelpSystems/GoAnywhere/config/
      - tomcatserver:/etc/HelpSystems/GoAnywhere/tomcat/conf/
      - ${HOME}/volumes/tomcatlogsdir:/opt/HelpSystems/GoAnywhere/tomcat/logs/
      - ${HOME}/volumes/ghttpsrootcustomdir:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
    depends_on:
      - mysqldb
volumes:
  userdata:
  configdir:
  tomcatserver:  
  mysql-data: