version: '3'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - default
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GADATA
      MYSQL_USER: GADATA
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
  mft1:
    image: myga:latest
    container_name: goanywhere-mft-1
    restart: unless-stopped
    networks:
      default:
        mac_address: 02:42:c0:a8:99:99
    ports:
      # Standard ports used by GoAnywhere MFT
      - "9000-9001:8000-8001"
      - "9005-9006:8005-8006"
      - "9009-9010:8009-8010"
      - "9443:9443"
      - "9021:8021"
      - "9990:8990"
      - "9022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
      #- "32001-32100:32001-32100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
      #- "32101-32200:32101-32200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
      #- "32201-32300:32201-32300"
    volumes:
      - /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
      - userdata1:/opt/HelpSystems/GoAnywhere/userdata/
      - upgraderlogs1:/opt/HelpSystems/GoAnywhere/upgrader/logs/
      - ${HOME}/volumes/configdir:/etc/HelpSystems/GoAnywhere/config/
      - tomcatserver1:/etc/HelpSystems/GoAnywhere/tomcat/conf/
      - tomcatlogsdir1:/opt/HelpSystems/GoAnywhere/tomcat/logs/
      - ghttpsrootcustomdir1:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
    depends_on:
      - mariadb
  mft2:
    image: myga:latest
    container_name: goanywhere-mft-2
    restart: unless-stopped
    networks:
      default:
        mac_address: 02:42:c0:a8:99:99
    ports:
      # Standard ports used by GoAnywhere MFT
      - "10000-10001:8000-8001"
      - "10005-10006:8005-8006"
      - "10009-10010:8009-8010"
      - "10443:9443"
      - "10021:8021"
      - "10990:8990"
      - "10022:8022"
      # Port range used for GoFast transfers, must match range set in service configuration to work properly.
      #- "33001-33100:32001-32100"
      # Port range used for passive FTP transfers, must match range set in service configuration to work properly.
      #- "33101-33200:32101-32200"
      # Port range used for passive FTPS transfers, must match range set in service configuration to work properly.
      #- "33201-33300:32201-32300"
    volumes:
      - /home/azureuser/volumes/gamft.lic:/opt/HelpSystems/GoAnywhere/gamft.lic
      - userdata2:/opt/HelpSystems/GoAnywhere/userdata/
      - upgraderlogs2:/opt/HelpSystems/GoAnywhere/upgrader/logs/
      - ${HOME}/volumes/configdir:/etc/HelpSystems/GoAnywhere/config/
      - tomcatserver2:/etc/HelpSystems/GoAnywhere/tomcat/conf/
      - tomcatlogsdir2:/opt/HelpSystems/GoAnywhere/tomcat/logs/
      - ghttpsrootcustomdir2:/opt/HelpSystems/GoAnywhere/ghttpsroot/custom/
    depends_on:
      - mariadb
volumes:
  tomcatserver1:
  tomcatserver2:
  mariadb-data:
  userdata1:
  userdata2:
  upgraderlogs1:
  upgraderlogs2:
  tomcatlogsdir1:
  tomcatlogsdir2:
  ghttpsrootcustomdir1:
  ghttpsrootcustomdir2: